#module_parameters(DEBUG := false);

#load "backend/opengl.jai";
#load "renderer2d.jai";

#load "core.jai";
#load "graphics.jai";
#load "font.jai";
#load "image.jai";

#scope_module

#import "Basic";
#import "StbTrueType";
#import "Hash_Table";
#import "Math";
#import "Math_Utils";
#import "Windows_Resources";

System     :: #import "System";
String     :: #import "String";
File       :: #import "File";
File_Utils :: #import "File_Utilities";